// Melhorias 14/09 — camada aditiva. Não remove gerências, BAs, métricas ou módulos existentes.
(()=>{
const MASTER='https://docs.google.com/spreadsheets/d/1XIjNk4xuYSEzG2Jw6rbBUJ-oymnSiuCj6QzuwBpnLYM/edit';
const sel=document.querySelector('#ba-select');
const scope=()=>sel?.value||'TODOS';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
// Corrige somente links da Master antiga.
document.querySelectorAll('a[href*="1ZfyRiL4b_ou_r-9dZD-7Eb_dNCl2a4TlsOukeVZdBjg"]').forEach(a=>a.href=a.href.replace('1ZfyRiL4b_ou_r-9dZD-7Eb_dNCl2a4TlsOukeVZdBjg','1XIjNk4xuYSEzG2Jw6rbBUJ-oymnSiuCj6QzuwBpnLYM'));
const snap=document.querySelector('.snapshot-note');if(snap)snap.innerHTML='<span class="live-dot"></span><strong>Master estratégica atualizada em 14/09/2026</strong> · BAM preserva execução; estratégia permanece na Master · <a href="'+MASTER+'" target="_blank" rel="noreferrer">abrir Master ↗</a>';

const clients={
'Julia Gutvilen':[['Blu / Blue Blazer','Botafogo','0/6','Perfect Serve; Visibilidade; Listing; Ativação; Treinamento; Preço'],['Xepa Bar','Botafogo','0/6','Perfect Serve; Visibilidade; Listing; Ativação; Treinamento; Preço'],['Vuvu','Botafogo','1/6','Perfect Serve; Visibilidade; Listing; Ativação; Treinamento'],['Boteco Rio’s - Barra da Tijuca','Barra / Olegário','4/6','Perfect Serve; Ativação'],['Cafofo Pub','Botafogo','0/6','Perfect Serve; Visibilidade; Listing; Ativação; Treinamento; Preço'],['Praia Club Reserva','Barra / Orla','0/6','Perfect Serve; Visibilidade; Listing; Ativação; Treinamento; Preço'],['Reserva Onze Beach Club','Barra / Orla','0/6','Perfect Serve; Visibilidade; Listing; Ativação; Treinamento; Preço'],['Mané Olegario','Barra / Olegário','0/6','Perfect Serve; Visibilidade; Listing; Ativação; Treinamento; Preço'],['Fonte Botafogo','Botafogo','0/6','Perfect Serve; Visibilidade; Listing; Ativação; Treinamento; Preço'],['Salva Botafogo','Botafogo','0/6','Perfect Serve; Visibilidade; Listing; Ativação; Treinamento; Preço']],
'João Pedro Marques':[['JANELA BAR TATUAPÉ','Tatuapé','5/6','Ativação'],["Pub St. John's Irish",'Tatuapé','5/6','Ativação'],['Serras Bar','Tatuapé','5/6','Ativação'],['Boteco Todos os Santos','Vila Madalena','4/6','Ativação; Treinamento'],['Odecasa - Albergue','Pinheiros','4/6','Ativação; Treinamento'],['Pracinha do Baixo','Pinheiros','4/6','Ativação; Treinamento'],['Penicilina','Pinheiros','3/6','Listing; Ativação; Treinamento'],['Starlane','Pinheiros','2/6','Visibilidade; Listing; Ativação; Treinamento'],['Bernadette Augusta','Baixo Augusta','6/6',''],['Barban Beer','Baixo Augusta','6/6','']],
'Maria Clarentino':[['Cine Clube Cortina','Centro / República','3/6','Perfect Serve; Ativação; Treinamento'],['Cordial','República','2/6','Perfect Serve; Visibilidade; Ativação; Treinamento'],['Formosa Hi-Fi','Centro / República','1/6','Perfect Serve; Visibilidade; Listing; Ativação; Treinamento'],['Balsa','Centro / República','1/6','Perfect Serve; Visibilidade; Listing; Ativação; Treinamento'],['Drosophyla','Consolação','1/6','Perfect Serve; Visibilidade; Listing; Ativação; Treinamento']],
'Mani Filardi':[['quitandinha','Pinheiros','3/6','Perfect Serve; Ativação; Treinamento'],['bar o quintal sbc','ABC','3/6','Listing; Ativação; Treinamento'],['Groove Bar','Pinheiros','1/6','Perfect Serve; Visibilidade; Listing; Ativação; Treinamento'],['GALO','Pinheiros','1/6','Perfect Serve; Visibilidade; Listing; Ativação; Treinamento'],['Guarita','Pinheiros','1/6','Perfect Serve; Visibilidade; Listing; Ativação; Treinamento'],['bella jau','Pinheiros','1/6','Perfect Serve; Visibilidade; Listing; Ativação; Treinamento']],
'Jerry Whilem':[['Boa Praça - Barra','Barra / Olegário','5/6','Treinamento'],['Aldeia / Aldeia Lagoa','Lagoa','4/6','Ativação; Preço'],['Caza Lagoa','Lagoa','4/6','Ativação; Preço'],['Coordenadas Bar','Botafogo','4/6','Ativação; Preço'],['Portal','Centro / Lapa','4/6','Ativação; Treinamento'],['Big Ben Pub','Botafogo','3/6','Listing; Ativação; Treinamento'],['Bosque Bar','Gávea','6/6','']]
};
function currentClients(){return clients[scope()]||[]}
function key(){return 'jager_plan_safe_'+scope()}
function load(){try{return JSON.parse(localStorage.getItem(key())||'[]')}catch{return[]}}
function save(v){localStorage.setItem(key(),JSON.stringify(v))}
function modal(html){document.querySelector('#safe-modal')?.remove();let d=document.createElement('div');d.id='safe-modal';d.className='safe-modal';d.innerHTML='<div class="safe-dialog"><button class="safe-x">×</button>'+html+'</div>';document.body.append(d);d.querySelector('.safe-x').onclick=()=>d.remove();d.onclick=e=>{if(e.target===d)d.remove()};return d}
function why(c){let n=parseInt(c[2])||0;if(n===5)return 'Está a 1 passo de virar PO — alto retorno por visita.';if(n===4)return 'Está próxima de PO — oportunidade de fechar gaps com baixo esforço.';if((c[3]||'').includes('Treinamento')&&(c[3]||'').includes('Ativação'))return 'Uma visita pode avançar execução e mais de um KPI.';return 'Prioridade sugerida pela situação operacional atual.'}
function actionFor(c){let g=(c[3]||'').split(';').map(x=>x.trim()).filter(Boolean);return g.length?'Resolver gaps ON6: '+g.join(', '):'Manter 6/6 e avançar próximo KPI'}
function addPlanBlock(){let view=document.querySelector('#acoes');if(!view)return;view.querySelector('#safe-plan')?.remove();let list=currentClients();if(!list.length)return;let saved=load(),rank=[...list].sort((a,b)=>{let score=x=>(parseInt(x[2])===5?100:parseInt(x[2])===4?80:parseInt(x[2])===3?60:0)+(x[3].includes('Treinamento')?20:0)+(x[3].includes('Ativação')?15:0);return score(b)-score(a)}).slice(0,8);let s=document.createElement('section');s.id='safe-plan';s.className='safe-plan';s.innerHTML='<div class="safe-head"><div><p class="eyebrow orange">META → PRIORIDADE → DECISÃO → SEMANA</p><h2>Planejamento assistido</h2><p>Complementa as ações existentes sem substituir a visão atual.</p></div><button id="safe-manual">+ Incluir ação</button></div><div class="safe-priority">'+rank.map((c,i)=>'<article><b>'+String(i+1).padStart(2,'0')+'</b><div><strong>'+esc(c[0])+'</strong><small>'+esc(c[1])+' · '+esc(c[2])+'</small><p>'+esc(why(c))+'</p><span>'+esc(actionFor(c))+'</span></div><button data-safe-add="'+i+'">Adicionar</button></article>').join('')+'</div>'+(saved.length?'<div class="safe-head"><div><p class="eyebrow">ESCOLHIDAS PELO BA</p><h3>Meu plano</h3></div></div><div class="safe-saved">'+saved.map((x,i)=>'<article><div><strong>'+esc(x.client)+'</strong><small>'+esc(x.route)+' · '+esc(x.date||'sem data')+'</small><span>'+esc(x.action)+'</span><em>'+esc(x.status)+'</em></div><button data-safe-del="'+i+'">×</button></article>').join('')+'</div>':'');let intro=view.querySelector('.page-intro');intro?intro.after(s):view.prepend(s);s.querySelector('#safe-manual').onclick=()=>openAction();s.querySelectorAll('[data-safe-add]').forEach(b=>b.onclick=()=>openAction(rank[+b.dataset.safeAdd][0]));s.querySelectorAll('[data-safe-del]').forEach(b=>b.onclick=()=>{let a=load();a.splice(+b.dataset.safeDel,1);save(a);addPlanBlock()})}
function openAction(pre){let list=currentClients();let d=modal('<p class="eyebrow orange">INCLUIR AÇÃO</p><h2>Decisão do BA</h2><label>Cliente<select id="s-client"><option value="">Escolha</option>'+list.map(c=>'<option '+(c[0]===pre?'selected':'')+'>'+esc(c[0])+'</option>').join('')+'</select></label><div id="s-context"></div><label>Ação<input id="s-action"></label><label>Quando<input id="s-date" type="date"></label><label>Observação<textarea id="s-note"></textarea></label><button id="s-save">Adicionar ao meu plano</button>');let q=d.querySelector('#s-client'),ctx=d.querySelector('#s-context'),act=d.querySelector('#s-action');function up(){let c=list.find(x=>x[0]===q.value);if(!c)return;ctx.innerHTML='<div class="safe-context"><strong>'+esc(c[2])+'</strong><span>'+esc(c[1])+'</span><p>'+(c[3]?'<b>Gaps:</b> '+esc(c[3]):'ON6 completo')+'</p><em>'+esc(why(c))+'</em></div>';act.value=actionFor(c)}q.onchange=up;up();d.querySelector('#s-save').onclick=()=>{let c=list.find(x=>x[0]===q.value);if(!c)return;let a=load();a.push({client:c[0],route:c[1],action:act.value,date:d.querySelector('#s-date').value,note:d.querySelector('#s-note').value,status:'Planejada'});save(a);d.remove();addPlanBlock()}}
function classifyButton(){let view=document.querySelector('#territorio');if(!view||view.querySelector('#safe-classify'))return;let btn=document.createElement('button');btn.id='safe-classify';btn.className='outline-button';btn.textContent='Classificar casa';view.querySelector('.page-intro')?.append(btn);btn.onclick=()=>{let list=currentClients();if(!list.length)return;let d=modal('<p class="eyebrow orange">LEITURA DE CAMPO</p><h2>Classificar casa</h2><label>Cliente<select id="c-client">'+list.map(c=>'<option>'+esc(c[0])+'</option>').join('')+'</select></label><label>Perfil / tipo<input id="c-profile"></label><label>Ocasião / consumidor<input id="c-occasion"></label><label>Potencial<select id="c-potential"><option>Alto</option><option>Médio</option><option>Baixo</option></select></label><label>Observação<textarea id="c-note"></textarea></label><button id="c-save">Salvar leitura</button><p class="safe-note">Leitura de campo do BA. Não altera automaticamente Casa Foco, Movimento, Papel ou Missão na Master.</p>');d.querySelector('#c-save').onclick=()=>{let a=JSON.parse(localStorage.getItem('jager_classifications_safe')||'[]');a.push({ba:scope(),client:d.querySelector('#c-client').value,profile:d.querySelector('#c-profile').value,occasion:d.querySelector('#c-occasion').value,potential:d.querySelector('#c-potential').value,note:d.querySelector('#c-note').value,at:new Date().toISOString()});localStorage.setItem('jager_classifications_safe',JSON.stringify(a));d.remove()}}}
let style=document.createElement('style');style.textContent='.safe-plan{margin:18px 0 28px}.safe-head{display:flex;justify-content:space-between;gap:18px;align-items:flex-start;margin:16px 0}.safe-head button,.safe-priority button,.safe-saved button,#s-save,#c-save{border:1px solid #d7ddd9;background:#fff;border-radius:9px;padding:9px 12px;font-weight:700}.safe-priority,.safe-saved{border:1px solid #dfe3e0;border-radius:13px;background:#fff;overflow:hidden}.safe-priority article{display:grid;grid-template-columns:34px 1fr auto;gap:12px;padding:13px;border-bottom:1px solid #edf0ee;align-items:center}.safe-priority article div,.safe-saved article div{display:flex;flex-direction:column;gap:3px}.safe-priority small,.safe-priority span,.safe-saved small,.safe-saved span{font-size:11px;color:#687169}.safe-priority p{margin:3px 0;font-size:13px}.safe-saved article{display:flex;justify-content:space-between;padding:12px 14px;border-bottom:1px solid #edf0ee}.safe-saved em{font-size:10px;font-style:normal;font-weight:800}.safe-modal{position:fixed;inset:0;background:rgba(6,18,12,.58);z-index:9999;display:flex;align-items:center;justify-content:center;padding:20px}.safe-dialog{width:min(720px,96vw);max-height:90vh;overflow:auto;background:#fff;border-radius:16px;padding:24px;position:relative}.safe-x{position:absolute;right:15px;top:10px;border:0;background:none;font-size:28px}.safe-dialog label{display:flex;flex-direction:column;gap:6px;margin:14px 0;font-weight:700;font-size:12px}.safe-dialog select,.safe-dialog input,.safe-dialog textarea{border:1px solid #cfd6d1;border-radius:9px;padding:10px;font:inherit}.safe-context{background:#f4f6f4;border-radius:10px;padding:12px;display:grid;gap:4px}.safe-note{font-size:11px;color:#687169}@media(max-width:760px){.safe-priority article{grid-template-columns:28px 1fr}.safe-priority article>button{grid-column:2}.safe-head{display:block}.safe-head button{margin-top:10px}}';document.head.append(style);
function refresh(){setTimeout(()=>{addPlanBlock();classifyButton()},0)}refresh();sel?.addEventListener('change',refresh);
})();